language: java
jdk:
- oraclejdk8
script: "mvn cobertura:cobertura"
after_success:
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
